spring:
  application:
    name: tech-challenge
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5433/fase1}
    username: ${DATASOURCE_USERNAME:application}
    password: ${DATASOURCE_PASSWORD:7KTu)$U9W1%7}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  liquibase:
    change-log: classpath:liquibase/db/changelog/db.changelog-master.xml
    enabled: true
security:
  token-secret: ${TOKEN_SECRET:ffb5914892f586c72016b717a1906676698124f695ba798a9da3f0ce6882768d1}
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dzihczwnp}
  api-key: ${CLOUDINARY_API_KEY:234725752194136}
  api_secret: ${CLOUDINARY_API_SECRET:cyZacpw4Dtmo2kzmjO8WjlV850U}